const { contextBridge, ipcRenderer } = require('electron')

contextBridge.exposeInMainWorld('drift', {
  ensureView: (id, url) => ipcRenderer.invoke('view:ensure', { id, url }),
  destroyView: (id) => ipcRenderer.invoke('view:destroy', { id }),
  loadURL: (id, url) => ipcRenderer.invoke('view:load', { id, url }),
  navAction: (id, action) => ipcRenderer.invoke('view:nav', { id, action }),
  layout: (payload) => ipcRenderer.send('view:layout', payload),
  raise: (id) => ipcRenderer.send('view:raise', id),
  snapshot: (id, width) => ipcRenderer.invoke('view:snapshot', { id, width }),
  saveState: (json) => ipcRenderer.invoke('state:save', json),
  loadState: () => ipcRenderer.invoke('state:load'),
  bookmarksLoad: () => ipcRenderer.invoke('bookmarks:load'),
  bookmarksSave: (data) => ipcRenderer.invoke('bookmarks:save', data),
  bookmarksExport: (html) => ipcRenderer.invoke('bookmarks:export', html),
  bookmarksImport: () => ipcRenderer.invoke('bookmarks:import'),
  vaultLoad: () => ipcRenderer.invoke('vault:load'),
  vaultSave: (blob) => ipcRenderer.invoke('vault:save', blob),
  vaultFill: (id, username, password) => ipcRenderer.invoke('vault:fill', { id, username, password }),
  selftestArtifact: (name, dataUrl) => ipcRenderer.invoke('selftest:artifact', { name, dataUrl }),
  selftestDone: (report) => ipcRenderer.invoke('selftest:done', report),
  openDownloadPage: () => ipcRenderer.invoke('update:open'),
  settingsLoad: () => ipcRenderer.invoke('settings:load'),
  settingsSave: (s) => ipcRenderer.invoke('settings:save', s),
  extList: () => ipcRenderer.invoke('ext:list'),
  extAdd: () => ipcRenderer.invoke('ext:add'),
  extRemove: (id) => ipcRenderer.invoke('ext:remove', id),
  onViewEvent: (fn) => ipcRenderer.on('view:event', (_e, d) => fn(d)),
  onUIKey: (fn) => ipcRenderer.on('ui:key', (_e, d) => fn(d)),
  onUpdateAvailable: (fn) => ipcRenderer.on('update:available', (_e, d) => fn(d))
})
